[dotfiles]
"zsh/zshrc" = "$HOME/zshrc.sh"
"zsh/" = "$HOME/.z"
"tmux/tmux.conf" = "$HOME/.tmux.conf"
"tilda/" = "$HOME/.config/tilda"
"fonts/" = "$HOME/.local/share/fonts"
"termux" = "$HOME/.termux"
"sshmount/sshfs_devices.toml" = "$HOME/.config/sshfs_devices.toml"

